name: CI

on:
  push:
    branches:
      - 'aplha/**'
      - 'beta/**'
      - 'demo/**'
  pull_request:
      # refs/heads にマッチするパターンのシーケンス
    branches:
      - 'main'
      - 'releases/**'
    # refs/heads にマッチするパターンのシーケンス
    tags:
      - 'v*.*'
    paths-ignore:
      - 'public/**'
      - 'docs/**'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.16.1

      - name: npm install
        run: npm install

      - name: npm test
        run: npm test
